// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GridQuickFixLayout
{
    internal sealed partial class Vsix
    {
        public const string Id = "GridQuickFixLayout.9379b1a7-03ad-4d69-a0de-59043e2b0b16";
        public const string Name = "Grid Quick Fix Layout";
        public const string Description = @"An extension that helps you increment, decrement, or fix sequences on grid columns and rows quickly.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Jerod Herzog";
        public const string Tags = "";
    }
}
