// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GridQuickFixLayout
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string GridQuickFixLayoutString = "62b4acbb-e1c9-4b13-921d-86734607fbc0";
        public static Guid GridQuickFixLayout = new Guid(GridQuickFixLayoutString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ButtonsGroup = 0x0001;
        public const int SubMenu = 0x0002;
        public const int SubMenuGroup = 0x0003;
        public const int GridColumnIncrementCommand = 0x0100;
        public const int GridColumnDecrementCommand = 0x0200;
        public const int GridColumnFillInSequenceCommand = 0x0300;
        public const int GridRowIncrementCommand = 0x0400;
        public const int GridRowDecrementCommand = 0x0500;
        public const int GridRowFillInSequenceCommand = 0x0600;
    }
}